import { AISuggestion, AIAnalysisResult } from './types';
import { medicalScales } from './scales-data';

/**
 * 🤖 ENHANCED AI ANALYZER - Sistema Auto-Actualizable
 * 
 * Este sistema se actualiza automáticamente cuando se agregan nuevas escalas médicas.
 * Los patrones se generan dinámicamente desde scales-data.ts
 * 
 * INSTRUCCIONES PARA CLAUDE CODE:
 * ================================
 * 
 * Cuando agregues una nueva escala médica:
 * 1. ✅ Agregar escala en scales-data.ts (se auto-actualiza)
 * 2. 🔧 Si la predicción no funciona bien, actualizar MEDICAL_SYNONYMS abajo
 * 3. 📝 Probar con texto de ejemplo para validar
 * 
 * Ejemplo de actualización:
 * Si agregas escala "MOCA" y no se detecta:
 * - Agregar: 'moca': ['montreal', 'evaluacion cognitiva', 'screening cognitivo']
 * 
 * NO TOCAR: Las funciones principales se actualizan solas
 */

// ============================================================================
// CONFIGURACIÓN DE SINÓNIMOS MÉDICOS
// ============================================================================
// 🔧 ÁREA EDITABLE: Agregar sinónimos aquí si las predicciones fallan
const MEDICAL_SYNONYMS: { [key: string]: string[] } = {
  // Neurológicos
  'ictus': ['stroke', 'avc', 'accidente cerebrovascular', 'derrame cerebral', 'embolia cerebral'],
  'temblor': ['temblores', 'shake', 'vibración', 'oscilación'],
  'parkinson': ['enfermedad de parkinson', 'parkinsonismo', 'ep'],
  'hemiparesia': ['hemiplejia', 'debilidad unilateral', 'parálisis parcial'],
  'disartria': ['habla arrastrada', 'dificultad hablar', 'lenguaje afectado'],
  'disfagia': ['dificultad tragar', 'problemas deglución'],
  'glasgow': ['escala glasgow', 'gcs', 'nivel conciencia'],
  'conciencia': ['consciencia', 'alerta', 'vigilia', 'awareness'],
  
  // Psiquiátricos - CRÍTICOS para detección
  'depresion': ['depresión', 'deprimido', 'depresivo', 'tristeza', 'melancolía', 'triste', 'bajo animo', 'estado animo'],
  'deprimido': ['depresión', 'depresivo', 'tristeza', 'melancolía', 'triste', 'bajo animo'],
  'depresivo': ['depresión', 'deprimido', 'tristeza', 'melancolía', 'triste'],
  'tristeza': ['depresión', 'deprimido', 'depresivo', 'melancolía', 'triste'],
  'major_depressive_disorder': ['depresión mayor', 'trastorno depresivo', 'episodio depresivo', 'deprimido', 'tristeza'],
  'beck': ['beck depression inventory', 'inventario beck', 'bdi', 'depresión beck'],
  'ansiedad': ['ansioso', 'nervioso', 'preocupación', 'angustia'],
  'suicida': ['suicidio', 'autolisis', 'pensamientos muerte', 'ideación suicida'],
  'anhedonia': ['falta placer', 'desinterés', 'apatía', 'pérdida interés'],
  'insomnio': ['problemas sueño', 'dificultad dormir', 'desvelo'],
  'demencia': ['deterioro cognitivo', 'alzheimer', 'pérdida memoria'],
  'agitacion': ['agitación', 'inquietud', 'hiperactividad', 'nerviosismo'],
  
  // Cardiovasculares
  'fibrilacion': ['fibrilación auricular', 'fa', 'arritmia', 'latido irregular'],
  'hemorragia': ['sangrado', 'hemorrhage', 'pérdida sangre'],
  'anticoagulacion': ['anticoagulante', 'warfarina', 'acenocumarol', 'sintrom'],
  
  // Cognitivos
  'memoria': ['recuerdo', 'recordar', 'amnesia', 'olvido'],
  'orientacion': ['orientación', 'desorientado', 'confuso', 'ubicación'],
  'concentracion': ['concentración', 'atención', 'foco', 'distracción'],
  
  // Escalas específicas
  'nihss': ['national institutes health stroke scale', 'escala stroke'],
  'updrs': ['unified parkinson disease rating scale', 'escala parkinson'],
  'mmse': ['mini mental', 'minimental', 'examen mental'],
  'moca': ['montreal cognitive assessment', 'evaluacion cognitiva montreal'],
  'rankin': ['modified rankin scale', 'mrs', 'escala rankin'],
  'ashworth': ['escala ashworth', 'tono muscular', 'espasticidad'],
  'midas': ['migraine disability assessment', 'discapacidad migraña'],
  'hit6': ['headache impact test', 'impacto cefalea']
};

// Lista de palabras negativas para detección de negaciones
const NEGATION_WORDS = [
  'sin', 'no', 'ausente', 'negativo', 'niega', 'descarta', 'ausencia',
  'libre', 'carece', 'falta', 'inexistente', 'nulo'
];

// Palabras que indican severidad/urgencia
const SEVERITY_INDICATORS = {
  high: ['severo', 'grave', 'intenso', 'agudo', 'crítico', 'urgente', 'emergencia'],
  moderate: ['moderado', 'intermedio', 'regular'],
  mild: ['leve', 'ligero', 'mínimo', 'poco', 'escaso']
};

// ============================================================================
// SISTEMA AUTO-GENERADOR DE PATRONES
// ============================================================================

interface AutoGeneratedPattern {
  scaleId: string;
  scaleName: string;
  category: string;
  keywords: string[];
  baseConfidence: number;
  reason: string;
}

/**
 * 🔄 AUTO-GENERA PATRONES desde scales-data.ts
 * Se ejecuta automáticamente - NO MODIFICAR
 */
const generatePatternsFromScales = (): AutoGeneratedPattern[] => {
  const patterns: AutoGeneratedPattern[] = [];
  
  medicalScales.forEach(scale => {
    const keywords: string[] = [];
    
    // 1. Extraer del nombre de la escala
    const nameKeywords = extractKeywordsFromText(scale.name.toLowerCase());
    keywords.push(...nameKeywords);
    
    // 2. Extraer de la descripción
    const descriptionKeywords = extractKeywordsFromText(scale.description.toLowerCase());
    keywords.push(...descriptionKeywords);
    
    // 3. Extraer de las etiquetas de los ítems
    scale.items.forEach(item => {
      const itemKeywords = extractKeywordsFromText(item.label.toLowerCase());
      keywords.push(...itemKeywords);
      
      // También de las opciones más importantes
      item.options.slice(0, 3).forEach(option => {
        const optionKeywords = extractKeywordsFromText(option.toLowerCase());
        keywords.push(...optionKeywords);
      });
    });
    
    // 4. Agregar sinónimos si existen
    const scaleIdKeywords = MEDICAL_SYNONYMS[scale.id] || [];
    keywords.push(...scaleIdKeywords);
    
    // Buscar sinónimos por palabras clave encontradas
    keywords.forEach(keyword => {
      const synonyms = MEDICAL_SYNONYMS[keyword] || [];
      keywords.push(...synonyms);
    });
    
    // 5. Limpiar y deduplicar keywords
    const cleanKeywords = [...new Set(keywords)]
      .filter(k => k && k.length > 2) // Palabras de al menos 3 caracteres
      .filter(k => !['0', '1', '2', '3', 'no', 'si', 'es', 'un', 'una', 'el', 'la'].includes(k));
    
    // 6. Determinar confianza base por categoría
    let baseConfidence = 0.7; // Por defecto
    
    if (scale.category.toLowerCase().includes('neurológic')) baseConfidence = 0.8;
    if (scale.category.toLowerCase().includes('psiquiátric')) baseConfidence = 0.85;
    if (scale.category.toLowerCase().includes('cognitiv')) baseConfidence = 0.8;
    if (scale.category.toLowerCase().includes('cardiovascular')) baseConfidence = 0.75;
    
    // 7. Crear el patrón
    patterns.push({
      scaleId: scale.id,
      scaleName: scale.name,
      category: scale.category,
      keywords: cleanKeywords,
      baseConfidence,
      reason: `Evaluación de ${scale.category.toLowerCase()}`
    });
  });
  
  console.log(`🔄 Auto-generated ${patterns.length} patterns from scales`);
  return patterns;
};

/**
 * Extrae palabras clave médicamente relevantes de un texto
 */
const extractKeywordsFromText = (text: string): string[] => {
  // Limpiar texto
  const cleanText = text
    .toLowerCase()
    .replace(/[^\wáéíóúñü\s]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
  
  const words = cleanText.split(' ');
  const keywords: string[] = [];
  
  // Extraer palabras individuales relevantes
  words.forEach(word => {
    if (word.length >= 3 && !['con', 'por', 'para', 'desde', 'hasta', 'entre'].includes(word)) {
      keywords.push(word);
    }
  });
  
  // Extraer frases de 2-3 palabras
  for (let i = 0; i < words.length - 1; i++) {
    const phrase2 = `${words[i]} ${words[i + 1]}`;
    if (phrase2.length >= 6) keywords.push(phrase2);
    
    if (i < words.length - 2) {
      const phrase3 = `${words[i]} ${words[i + 1]} ${words[i + 2]}`;
      if (phrase3.length >= 10) keywords.push(phrase3);
    }
  }
  
  return keywords;
};

// ============================================================================
// ANÁLISIS CONTEXTUAL MEJORADO
// ============================================================================

/**
 * Normaliza texto para análisis (sin acentos, minúsculas)
 */
const normalizeText = (text: string): string => {
  return text
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^\w\s]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
};

/**
 * 🔍 ANÁLISIS DE NEGACIONES MEJORADO
 * Detecta si los síntomas están siendo negados
 */
const analyzeNegations = (text: string, keyword: string): number => {
  const normalizedText = normalizeText(text);
  const words = normalizedText.split(' ');
  
  // Buscar posición del keyword
  let keywordPosition = -1;
  for (let i = 0; i < words.length; i++) {
    if (words.slice(i, i + keyword.split(' ').length).join(' ').includes(keyword)) {
      keywordPosition = i;
      break;
    }
  }
  
  if (keywordPosition === -1) return 1; // No encontrado, confianza normal
  
  // Buscar negaciones en las 5 palabras anteriores al keyword
  const contextStart = Math.max(0, keywordPosition - 5);
  const contextWords = words.slice(contextStart, keywordPosition + 1);
  
  for (const negWord of NEGATION_WORDS) {
    if (contextWords.includes(normalizeText(negWord))) {
      console.log(`❌ Negation detected: "${negWord}" near "${keyword}"`);
      return 0.1; // Reducir confianza significativamente
    }
  }
  
  return 1; // Sin negación detectada
};

/**
 * 🎯 ANÁLISIS DE PROXIMIDAD
 * Calcula si las palabras clave están cerca unas de otras
 */
const calculateProximityScore = (text: string, keywords: string[]): number => {
  const normalizedText = normalizeText(text);
  const words = normalizedText.split(' ');
  const keywordPositions: number[] = [];
  
  // Encontrar posiciones de todos los keywords
  keywords.forEach(keyword => {
    const normalizedKeyword = normalizeText(keyword);
    for (let i = 0; i < words.length; i++) {
      if (words[i].includes(normalizedKeyword) || normalizedKeyword.includes(words[i])) {
        keywordPositions.push(i);
      }
    }
  });
  
  if (keywordPositions.length < 2) return 1;
  
  // Calcular distancia promedio entre keywords
  let totalDistance = 0;
  let pairs = 0;
  
  for (let i = 0; i < keywordPositions.length; i++) {
    for (let j = i + 1; j < keywordPositions.length; j++) {
      totalDistance += Math.abs(keywordPositions[i] - keywordPositions[j]);
      pairs++;
    }
  }
  
  const avgDistance = totalDistance / pairs;
  
  // Boost si las palabras están cerca (distancia < 10 palabras)
  if (avgDistance < 10) return 1.3;
  if (avgDistance < 20) return 1.1;
  
  return 1;
};

/**
 * 📊 ANÁLISIS DE SEVERIDAD
 * Detecta indicadores de severidad en el texto
 */
const analyzeSeverity = (text: string): { level: string; multiplier: number } => {
  const normalizedText = normalizeText(text);
  
  // Buscar indicadores de alta severidad
  for (const indicator of SEVERITY_INDICATORS.high) {
    if (normalizedText.includes(normalizeText(indicator))) {
      return { level: 'high', multiplier: 1.5 };
    }
  }
  
  // Buscar indicadores de severidad moderada
  for (const indicator of SEVERITY_INDICATORS.moderate) {
    if (normalizedText.includes(normalizeText(indicator))) {
      return { level: 'moderate', multiplier: 1.2 };
    }
  }
  
  // Buscar indicadores de severidad leve
  for (const indicator of SEVERITY_INDICATORS.mild) {
    if (normalizedText.includes(normalizeText(indicator))) {
      return { level: 'mild', multiplier: 0.9 };
    }
  }
  
  return { level: 'normal', multiplier: 1 };
};

/**
 * 🧮 CÁLCULO DE CONFIANZA MEJORADO
 * Combina múltiples factores para una predicción más precisa
 */
const calculateEnhancedConfidence = (
  normalizedText: string, 
  pattern: AutoGeneratedPattern
): number => {
  const words = normalizedText.split(' ');
  const matchedKeywords: string[] = [];
  let totalNegationFactor = 1;
  
  console.log(`🔍 Testing pattern ${pattern.scaleId} against text:`, normalizedText.substring(0, 100));
  console.log(`📝 Pattern keywords:`, pattern.keywords.slice(0, 10));
  
  // 1. Buscar coincidencias de keywords
  pattern.keywords.forEach(keyword => {
    const normalizedKeyword = normalizeText(keyword);
    
    if (normalizedText.includes(normalizedKeyword)) {
      matchedKeywords.push(keyword);
      
      // Aplicar análisis de negación
      const negationFactor = analyzeNegations(normalizedText, normalizedKeyword);
      totalNegationFactor *= negationFactor;
      
      console.log(`  ✅ MATCH: "${keyword}" (negation: ${negationFactor})`);
    }
  });
  
  if (matchedKeywords.length === 0) return 0;
  
  // 2. Factores base
  const keywordRatio = matchedKeywords.length / pattern.keywords.length;
  const textLengthFactor = Math.min(words.length / 50, 1);
  const baseConfidence = pattern.baseConfidence;
  
  // 3. Análisis de proximidad
  const proximityScore = calculateProximityScore(normalizedText, matchedKeywords);
  
  // 4. Análisis de severidad
  const severity = analyzeSeverity(normalizedText);
  
  // 5. Combinación de factores
  let confidence = baseConfidence * keywordRatio * (0.5 + 0.5 * textLengthFactor);
  
  // Aplicar multiplicadores
  confidence *= totalNegationFactor; // Negaciones
  confidence *= proximityScore; // Proximidad
  confidence *= severity.multiplier; // Severidad
  
  // Boosts por número de matches
  if (matchedKeywords.length >= 3) confidence *= 1.4;
  else if (matchedKeywords.length >= 2) confidence *= 1.2;
  
  // Boost por categoría especializada
  if (pattern.category.toLowerCase().includes('psiquiátric') || 
      pattern.category.toLowerCase().includes('cognitiv')) {
    confidence *= 1.3;
  }
  
  console.log(`  📈 Enhanced confidence: ${confidence.toFixed(3)} ` +
    `(matches: ${matchedKeywords.length}, proximity: ${proximityScore}, ` +
    `severity: ${severity.level}, negation: ${totalNegationFactor})`);
  
  return Math.min(confidence, 1);
};

// ============================================================================
// FUNCIÓN PRINCIPAL DE ANÁLISIS
// ============================================================================

/**
 * 🚀 ANÁLISIS PRINCIPAL MEJORADO
 * Combina auto-generación de patrones con análisis contextual avanzado
 */
export const analyzeTextEnhanced = (text: string): AIAnalysisResult => {
  console.log('🚀 Enhanced AI Analyzer - Analyzing text:', text.substring(0, 100) + '...');
  
  if (!text || text.trim().length < 5) { // Reducido de 10 a 5
    console.log('❌ Text too short, skipping analysis');
    return {
      suggestions: [],
      timestamp: Date.now()
    };
  }
  
  // DEBUGGING ESPECIAL PARA "DEPRIMIDO"
  if (text.toLowerCase().includes('deprimido')) {
    console.log('🔍 DEBUGGING: Detectado "deprimido" en el texto');
  }
  
  // 1. Auto-generar patrones desde las escalas
  const autoPatterns = generatePatternsFromScales();
  
  // 2. Normalizar texto
  const normalizedText = normalizeText(text);
  const suggestions: AISuggestion[] = [];
  
  // DETECCIÓN INTELIGENTE - Incluye variaciones de género y categorías
  const smartDetections: { [key: string]: string[] } = {
    // Psiquiátricas - Variaciones de género y términos
    'deprimid': ['major_depressive_disorder', 'beck_depression_inventory'], // captura deprimido/deprimida
    'depresiv': ['major_depressive_disorder', 'beck_depression_inventory'], // captura depresivo/depresiva
    'depresion': ['major_depressive_disorder', 'beck_depression_inventory'],
    'tristeza': ['major_depressive_disorder', 'beck_depression_inventory'],
    'triste': ['major_depressive_disorder', 'beck_depression_inventory'],
    'melancolico': ['major_depressive_disorder', 'beck_depression_inventory'],
    'melancolica': ['major_depressive_disorder', 'beck_depression_inventory'],
    'suicid': ['major_depressive_disorder', 'beck_depression_inventory'], // suicida/suicidio
    'ansiedad': ['major_depressive_disorder', 'beck_depression_inventory'],
    'ansios': ['major_depressive_disorder', 'beck_depression_inventory'], // ansioso/ansiosa
    
    // Neurológicas - Parkinson
    'temblor': ['parkinson_diagnosis', 'updrs3', 'hoehn_yahr'],
    'parkinson': ['parkinson_diagnosis', 'updrs1', 'updrs3', 'hoehn_yahr'],
    'rigidez': ['parkinson_diagnosis', 'updrs3', 'ashworth'],
    'bradicinesia': ['parkinson_diagnosis', 'updrs3'],
    'bradiquinesia': ['parkinson_diagnosis', 'updrs3'],
    'festinacion': ['parkinson_diagnosis', 'updrs2'],
    
    // Neurológicas - Stroke
    'hemiparesia': ['nihss', 'mrs'],
    'hemiplejia': ['nihss', 'mrs'],
    'disartria': ['nihss'],
    'disfagia': ['nihss'],
    'stroke': ['nihss', 'mrs'],
    'ictus': ['nihss', 'mrs', 'aspects'],
    'avc': ['nihss', 'mrs'],
    
    // Cognitivas
    'memoria': ['mmse', 'moca'],
    'olvid': ['mmse', 'moca'], // olvido/olvidos
    'confus': ['mmse', 'moca', 'glasgow'], // confuso/confusa/confusión
    'desorient': ['mmse', 'moca'], // desorientado/desorientada/desorientación
    'demencia': ['mmse', 'moca', 'neuropsychiatric_inventory'],
    'alzheimer': ['mmse', 'moca', 'neuropsychiatric_inventory'],
    'cognitiv': ['mmse', 'moca'], // cognitivo/cognitiva
    
    // Neuropsiquiátricas
    'agitacion': ['neuropsychiatric_inventory'],
    'agitad': ['neuropsychiatric_inventory'], // agitado/agitada
    'alucinacion': ['neuropsychiatric_inventory'],
    'alucinand': ['neuropsychiatric_inventory'], // alucinando
    'deliri': ['neuropsychiatric_inventory'], // delirio/delirante
    'comportamiento': ['neuropsychiatric_inventory'],
    
    // Cefalea
    'cefalea': ['midas', 'hit6'],
    'migrana': ['midas', 'hit6'],
    'dolor cabeza': ['midas', 'hit6'],
    'dolor de cabeza': ['midas', 'hit6'],
    
    // Glasgow/Conciencia
    'glasgow': ['glasgow'],
    'conciencia': ['glasgow', 'nihss'],
    'coma': ['glasgow', 'nihss'],
    'estupor': ['glasgow']
  };
  
  // DETECCIÓN POR CATEGORÍAS MÉDICAS
  const categoryDetections: { [key: string]: string[] } = {
    'psiquiatria': ['major_depressive_disorder', 'beck_depression_inventory', 'neuropsychiatric_inventory'],
    'psiquiatrica': ['major_depressive_disorder', 'beck_depression_inventory', 'neuropsychiatric_inventory'],
    'psiquiatrico': ['major_depressive_disorder', 'beck_depression_inventory', 'neuropsychiatric_inventory'],
    'neurologia': ['nihss', 'glasgow', 'updrs1', 'updrs3', 'parkinson_diagnosis', 'hoehn_yahr'],
    'neurologica': ['nihss', 'glasgow', 'updrs1', 'updrs3', 'parkinson_diagnosis', 'hoehn_yahr'],
    'neurologico': ['nihss', 'glasgow', 'updrs1', 'updrs3', 'parkinson_diagnosis', 'hoehn_yahr'],
    'cognitiva': ['mmse', 'moca'],
    'cognitivo': ['mmse', 'moca'],
    'cardiovascular': ['cha2ds2vasc', 'hasbled'],
    'cardiologia': ['cha2ds2vasc', 'hasbled']
  };

  // Buscar detecciones inteligentes (con variaciones de género)
  Object.keys(smartDetections).forEach(keyword => {
    if (normalizedText.includes(keyword)) {
      console.log(`🎯 SMART DETECTION: "${keyword}" found in text`);
      smartDetections[keyword].forEach(scaleId => {
        suggestions.push({
          scaleId,
          confidence: 0.9,
          keywords: [keyword],
          reason: `Detección inteligente de "${keyword}"`
        });
      });
    }
  });

  // Buscar detecciones por categoría médica
  Object.keys(categoryDetections).forEach(category => {
    if (normalizedText.includes(category)) {
      console.log(`🏥 CATEGORY DETECTION: "${category}" found in text`);
      categoryDetections[category].forEach(scaleId => {
        suggestions.push({
          scaleId,
          confidence: 0.8, // Ligeramente menor que detección directa
          keywords: [category],
          reason: `Detección por categoría "${category}"`
        });
      });
    }
  });
  
  // 3. Analizar cada patrón
  autoPatterns.forEach(pattern => {
    const confidence = calculateEnhancedConfidence(normalizedText, pattern);
    
    // Umbral ultra-sensible para detección médica
    if (confidence >= 0.05) {
      const matchedKeywords = pattern.keywords.filter(keyword => 
        normalizedText.includes(normalizeText(keyword))
      );
      
      suggestions.push({
        scaleId: pattern.scaleId,
        confidence,
        keywords: matchedKeywords,
        reason: pattern.reason
      });
    }
  });
  
  // 4. Deduplicar sugerencias (evitar escalas repetidas)
  const uniqueSuggestions = suggestions.reduce((acc, current) => {
    const exists = acc.find(item => item.scaleId === current.scaleId);
    if (!exists) {
      acc.push(current);
    } else if (current.confidence > exists.confidence) {
      // Reemplazar si la nueva tiene mayor confianza
      const index = acc.findIndex(item => item.scaleId === current.scaleId);
      acc[index] = current;
    }
    return acc;
  }, [] as AISuggestion[]);
  
  // 5. Ordenar y limitar resultados
  uniqueSuggestions.sort((a, b) => b.confidence - a.confidence);
  const topSuggestions = uniqueSuggestions.slice(0, 6);
  
  console.log('✅ Enhanced Analyzer - Found suggestions:', topSuggestions.length);
  console.log('📊 Top suggestions:', topSuggestions.map(s => 
    `${s.scaleId}: ${s.confidence.toFixed(3)}`).join(', '));
  
  // DEBUGGING FINAL
  if (topSuggestions.length === 0 && text.length > 5) {
    console.warn('⚠️ NO SUGGESTIONS FOUND for text:', text);
    console.warn('⚠️ Normalized text:', normalizedText);
  }
  
  return {
    suggestions: topSuggestions,
    timestamp: Date.now()
  };
};

// ============================================================================
// HOOK PARA REACT CON DEBOUNCING
// ============================================================================

import { useState, useEffect } from 'react';

export const useEnhancedAIAnalysis = (text: string, delay: number = 1000) => {
  const [analysis, setAnalysis] = useState<AIAnalysisResult>({
    suggestions: [],
    timestamp: Date.now()
  });
  
  useEffect(() => {
    const timer = setTimeout(() => {
      const result = analyzeTextEnhanced(text);
      setAnalysis(result);
    }, delay);
    
    return () => clearTimeout(timer);
  }, [text, delay]);
  
  return analysis;
};

// ============================================================================
// FUNCIONES DE UTILIDAD PARA DEBUGGEO
// ============================================================================

/**
 * 🔧 FUNCIÓN DE DEBUG - Ver patrones generados
 * Útil para debugging y verificación
 */
export const debugPatterns = () => {
  const patterns = generatePatternsFromScales();
  console.table(patterns.map(p => ({
    Scale: p.scaleId,
    Keywords: p.keywords.slice(0, 5).join(', ') + '...',
    Total: p.keywords.length,
    Confidence: p.baseConfidence
  })));
  return patterns;
};

/**
 * 🧪 FUNCIÓN DE TEST - Probar análisis con texto
 */
export const testAnalysis = (text: string, expectedScales: string[] = []) => {
  const result = analyzeTextEnhanced(text);
  console.log('\n🧪 TEST RESULTS:');
  console.log('Input:', text.substring(0, 100));
  console.log('Expected scales:', expectedScales);
  console.log('Found suggestions:', result.suggestions.map(s => s.scaleId));
  
  const found = result.suggestions.map(s => s.scaleId);
  const success = expectedScales.every(scale => found.includes(scale));
  console.log(success ? '✅ TEST PASSED' : '❌ TEST FAILED');
  
  return { result, success };
};

// ============================================================================
// EXPORTAR FUNCIONES GLOBALMENTE PARA DEBUG EN BROWSER
// ============================================================================

// Hacer funciones disponibles globalmente para debugging
if (typeof window !== 'undefined') {
  (window as any).analyzeTextEnhanced = analyzeTextEnhanced;
  (window as any).debugPatterns = debugPatterns;
  (window as any).testAnalysis = testAnalysis;
  
  console.log('🤖 Enhanced AI Analyzer cargado. Funciones disponibles:');
  console.log('   - analyzeTextEnhanced(text)');
  console.log('   - debugPatterns()');
  console.log('   - testAnalysis(text, expectedScales)');
}